version: '3.4'

services:
  server:
    container_name: cocktails-static-${CONTAINER_NS}
    image: registry.fritsler.ru/cocktail-library-static:${BUILD_VER}
    restart: always
    env_file:
      - .env
    ports:
      - "${COCKTAILS_STATIC__SERVER_PORT}:4030"
    volumes:
      - cocktail-library-static-storage:/app/cocktail-library-static-storage/
      - cocktail-library-static-sqlite:/app/cocktail-static-db.sqlite

volumes:
  cocktail-library-static-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${COCKTAILS_STATIC__MACHINE_STORAGE_PATH}/
  cocktail-library-static-sqlite:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${COCKTAILS_STATIC__MACHINE_SQLITE_PATH}/
  