version: '3.4'

services:
  server:
    container_name: cocktails-static-${CONTAINER_NS}
    image: registry.fritsler.ru/cocktail-library-static:${BUILD_VER}
    restart: always
    env_file:
      - .env
    ports:
      - "${COCKTAILS_STATIC__SERVER_PORT}:4030"
    volumes:
      - ${COCKTAILS_STATIC__MACHINE_STORAGE_PATH}/:/app/cocktail-library-static-storage/
      - ${COCKTAILS_STATIC__MACHINE_SQLITE_PATH}:/app/cocktail-static-db.sqlite
